// One catalogue powers /pomoc, autocomplete, slash descriptions and KOMENDY.md.
const entry = (category, tier, summary, usage, details) => ({ category, tier, summary, usage, details });
export const categories = {
  start: 'Start i informacje', profil: 'Profil i poziomy', ekonomia: 'Ekonomia i bank', sklep:'Sklep i kolekcja',
  zabawa: 'Zabawa i ankiety', glos: 'Pokoje głosowe', moderacja: 'Moderacja', zarzadzanie: 'Zarządzanie',
};
export const commandMeta = {
  weekly: entry('ekonomia',0,'Odbierz 1200 wirtualnych monet raz na 7 dni.','/weekly','Termin wynosi 7 × 24 godziny od poprzedniego odbioru. Nagroda nie zależy od dnia tygodnia.'),
  bank: entry('ekonomia',0,'Sprawdź bank i przenoś monety między portfelem a oszczędnościami.','/bank saldo | wplac ilosc:500 | wyplac ilosc:500','Przelewy wewnętrzne bez prowizji. Bank nie nalicza odsetek. Gry i sklep używają tylko monet w portfelu.'),
  osiagniecia: entry('profil',0,'Sprawdź 8 osiągnięć, postęp i odbierz jednorazowe nagrody.','/osiagniecia','Ukończone osiągnięcia odbierasz przyciskiem. Zapis w bazie zapobiega ponownemu odbiorowi po restarcie.'),
  personalizacja: entry('sklep',0,'Zobacz wygląd swojego profilu albo przywróć motyw i ramkę domyślną.','/personalizacja podglad | reset','Kupione motywy i ramki zakładasz przez /uzyj lub /plecak. Reset nie usuwa przedmiotów ani tytułu.'),
  ekonomia: entry('ekonomia',0,'Otwórz prywatny dashboard portfela, banku, historii i nagród.','/ekonomia','Canvas pokazuje faktyczny przepływ monet przez ostatnie 7 dni (UTC), wydatki, nagrody i dostępność daily/pracy/weekly.'),
  pomoc: entry('start',0,'Pomoc z kategoriami, przykładami i wymaganiami komend.','/pomoc [kategoria] [komenda]','Wybierz kategorię w menu lub wpisz nazwę konkretnej komendy. Pomoc jest widoczna tylko dla Ciebie.'),
  ping: entry('start',0,'Sprawdź opóźnienie połączenia z Discordem i czas pracy bota.','/ping','Pokazuje opóźnienie WebSocket. Chwilowy brak pomiaru po starcie nie oznacza awarii.'),
  userinfo: entry('start',0,'Zobacz datę dołączenia, role i statystyki wskazanej osoby.','/userinfo [osoba] [prywatnie]','Domyślnie wyświetla Twoje dane. Pokazuje maksymalnie 12 najwyższych ról.'),
  serverinfo: entry('start',0,'Zobacz liczebność, kanały, boosty i datę powstania serwera.','/serverinfo','Statystyki pochodzą z danych serwera dostępnych botowi.'),
  avatar: entry('start',0,'Wyświetl duży awatar użytkownika i link do obrazu.','/avatar [osoba] [prywatnie]','Używa awatara serwerowego, a gdy go nie ma — globalnego.'),
  botinfo: entry('start',0,'Sprawdź wersję, czas pracy i możliwości bota Wymiar ZERQONA.','/botinfo','Informacje o bieżącym procesie bota i skróty do najważniejszych funkcji.'),
  profil: entry('profil',0,'Karta profilu: poziom, tytuł, monety, XP i aktywność.','/profil [osoba] [prywatnie]','Przyciski przełączają profil, rangę i portfel wskazanej osoby. Wiadomości oznaczają tylko te nagrodzone XP.'),
  ranga: entry('profil',0,'Karta poziomu: miejsce w rankingu i XP do awansu.','/ranga [osoba] [prywatnie]','Pokazuje bieżący poziom, dokładny postęp i brakujące XP. Ranking obejmuje zapisane profile; remisy rozstrzyga ID.'),
  top: entry('profil',0,'Rankingi XP, portfela, majątku, banku, wiadomości i VC — z kolejnymi stronami.','/top [typ] [strona] [prywatnie]','10 osób na stronę. Dane obejmują profile zapisane w bazie, również osób, które opuściły serwer.'),
  poziomy: entry('profil',0,'Sprawdź progi ról, zasady XP oraz premie za poziomy.','/poziomy','12–18 XP za tekst co 45 s, 8 XP/min za aktywne VC. Booster 2× i Iskra 1,5× dają razem 3×; Przebudzenie z Boosterem daje 4×.'),
  portfel: entry('ekonomia',0,'Karta monet, pozycji w rankingu i dostępności nagród.','/portfel [osoba] [prywatnie]','Monety są wirtualną walutą serwera. Przełączniki prowadzą do profilu i rangi.'),
  daily: entry('ekonomia',0,'Odbierz 350–650 monet co 24 h; utrzymuj serię kolejnych odbiorów.','/daily','Pierwszy odbiór: 350. Każdy kolejny: +50, maks. 650 od 7. odbioru. Przerwa ponad 48 h resetuje serię.'),
  praca: entry('ekonomia',0,'Wykonaj zadanie i odbierz losowo 100–240 monet co 45 minut.','/praca','Nagroda trafia od razu do portfela. /nagrody pokazuje dokładny termin następnej pracy.'),
  nagrody: entry('ekonomia',0,'Sprawdź terminy daily i pracy, serię oraz aktywne bonusy XP.','/nagrody','Prywatny panel Twoich nagród. Przedłużenie Iskry dodaje czas, nie kolejny mnożnik.'),
  przelew: entry('ekonomia',0,'Przekaż od 1 do 1 000 000 000 monet innej osobie na serwerze.','/przelew osoba:@osoba ilosc:500','Bez prowizji. Nie możesz wysłać monet sobie ani botowi. Operacja zapisuje się w historii obu osób.'),
  historia: entry('ekonomia',0,'Zobacz do 15 ostatnich operacji swojego portfela.','/historia [ile]','Prywatna historia od wersji 2.0: nagrody, sklep, gry, przelewy i korekty administracji.'),
  sklep: entry('sklep',0,'Przeglądaj przedmioty, ceny, stan posiadania i przyciski zakupu.','/sklep [kategoria]','Canvas pokazuje ceny, rzadkość, czas efektu i stan kolekcji. Filtruj kategorie oraz strony i kupuj przyciskiem.'),
  kup: entry('sklep',0,'Kup boost, tytuł, motyw karty lub ramkę awatara za monety z portfela.','/kup przedmiot:xp_boost','Zakup nie aktywuje przedmiotu. Użyj /uzyj. Ponowny zakup posiadanego tytułu jest zablokowany.'),
  plecak: entry('sklep',0,'Sprawdź przedmioty, posiadane tytuły i aktywny bonus XP.','/plecak','Tytuły możesz zakładać bez zużywania. Iskry znikają z plecaka po aktywacji.'),
  uzyj: entry('sklep',0,'Aktywuj posiadany bonus XP albo załóż kupiony tytuł.','/uzyj przedmiot:xp_boost','Podpowiedzi pokazują Twój plecak. Boosty tego samego mnożnika wydłużają czas; różne mnożniki tego samego rodzaju nie łączą się. Motywy i ramki zmieniają karty.'),
  tytul: entry('sklep',0,'Zdejmij tytuł z karty, zachowując go w swojej kolekcji.','/tytul zdejmij','Aby ponownie założyć tytuł, użyj /uzyj przedmiot:<tytuł>.'),
  moneta: entry('zabawa',0,'Wybierz orła lub reszkę; opcjonalnie zagraj o wirtualne monety.','/moneta strona:orzel [stawka:100]','Obie strony mają szansę 50%. Trafienie wypłaca 2× stawkę (zysk 1×), przegrana zabiera stawkę.'),
  sloty: entry('zabawa',0,'Losuj 3 symbole; para płaci 1,5×, trójka 5×, trzy diamenty 8×.','/sloty stawka:100','Stawka 1–100 000. Mnożniki oznaczają całą wypłatę, razem ze stawką; wynik jest zaokrąglany w dół. To wirtualne monety.'),
  kostka: entry('zabawa',0,'Rzuć kością o wybranej liczbie ścian: od 2 do 100.','/kostka [sciany:20]','Domyślnie klasyczna kostka sześciościenna. Komenda nie pobiera monet.'),
  wrozba: entry('zabawa',0,'Zadaj pytanie i otrzymaj losową odpowiedź Wyroczni Wymiaru.','/wrozba pytanie:Czy dziś wygram?','Losowa odpowiedź dla zabawy, bez wpływu na XP i portfel.'),
  kpn: entry('zabawa',0,'Zagraj z botem w kamień, papier, nożyce — bez stawki.','/kpn wybor:kamien','Papier wygrywa z kamieniem, kamień z nożycami, nożyce z papierem.'),
  ankieta: entry('zabawa',0,'Utwórz ankietę z 2–4 różnymi opcjami i reakcjami do głosowania.','/ankieta pytanie:W co gramy? opcja1:Roblox opcja2:CS2','Każda osoba może zaznaczyć kilka reakcji. Ankieta nie zamyka się automatycznie. Bot potrzebuje Add Reactions i Read Message History.'),
  pokoj: entry('glos',0,'Otwórz panel nazwy, limitu, dostępu i właściciela pokoju VC.','/pokoj','Wejdź do lobby, aby utworzyć pokój. Panel jest dostępny w jego czacie. Pusty pokój znika po 30 sekundach.'),
  ostrzezenia: entry('moderacja',0,'Pokaż własne ostrzeżenia; ekipa może sprawdzać inne osoby.','/ostrzezenia [osoba]','Prywatny widok ostatnich 15 ostrzeżeń. Każde ma numer, powód, datę i moderatora.'),
  warn: entry('moderacja',1,'Zapisz ostrzeżenie z powodem i numerem sprawy.','/warn osoba:@osoba powod:Powód','Wymagana rola Helper lub wyższa. Obowiązuje hierarchia ról. Sam warn nie nakłada timeoutu.'),
  unwarn: entry('moderacja',1,'Usuń ostrzeżenie po jego numerze, z kontrolą hierarchii ról.','/unwarn numer:12','Numer odczytasz w /ostrzezenia. Usunięcie trafia do logu ekipy.'),
  wyczysc: entry('moderacja',1,'Usuń 1–100 ostatnich wiadomości młodszych niż 14 dni.','/wyczysc ilosc:25','Bot potrzebuje Manage Messages i Read Message History. Wynik podaje faktyczną liczbę usuniętych wiadomości.'),
  timeout: entry('moderacja',2,'Ogranicz komunikację użytkownika na 1–40 320 minut.','/timeout osoba:@osoba minuty:60 powod:Powód','Maksymalnie 28 dni. Bot potrzebuje Moderate Members. Nie działa na właściciela ani administratorów.'),
  untimeout: entry('moderacja',2,'Zakończ aktywny timeout użytkownika, zapisując powód.','/untimeout osoba:@osoba powod:Powód','Zdejmuje przerwę Discord; nie zmienia ról ani stanu wyciszenia mikrofonu.'),
  mute: entry('moderacja',2,'Alias /timeout: ogranicz komunikację na podaną liczbę minut.','/mute osoba:@osoba minuty:60 powod:Powód','Używa systemu timeout Discord. To nie jest osobna rola Mute ani wyciszenie mikrofonu.'),
  unmute: entry('moderacja',2,'Alias /untimeout: zakończ przerwę w komunikacji.','/unmute osoba:@osoba powod:Powód','Działa tak samo jak /untimeout.'),
  kick: entry('moderacja',2,'Wyrzuć osobę z serwera i zapisz powód w logu.','/kick osoba:@osoba powod:Powód','Osoba może wrócić przez nowe zaproszenie. Bot potrzebuje Kick Members i wyższej roli.'),
  ban: entry('moderacja',2,'Zbanuj członka serwera, zachowując jego wiadomości.','/ban osoba:@osoba powod:Powód','Bot potrzebuje Ban Members i wyższej roli. Zdjęcie bana: /unban.'),
  unban: entry('moderacja',2,'Zdejmij bana po ID użytkownika i zapisz powód.','/unban id:123456789012345678 powod:Powód','ID odczytasz z logów lub trybu deweloperskiego Discord. Osoba musi mieć aktywnego bana.'),
  slowmode: entry('moderacja',2,'Ustaw odstęp między wiadomościami: 0–21 600 sekund.','/slowmode sekundy:10','Wartość 0 wyłącza slowmode. Zmiana dotyczy kanału, na którym użyto komendy.'),
  zamknij: entry('moderacja',2,'Zablokuj pisanie dla @everyone i zapamiętaj poprzednie ustawienie.','/zamknij','Nie zmienia indywidualnych nadpisań ról/członków. Osoby z osobnym zezwoleniem lub Administrator nadal mogą pisać.'),
  otworz: entry('moderacja',2,'Przywróć uprawnienie pisania sprzed /zamknij.','/otworz','Odtwarza zapisane ustawienie @everyone. Bez zapisanej blokady nie zmienia kanału.'),
  rola: entry('zarzadzanie',3,'Nadaj lub zdejmij rolę z kontrolą hierarchii i ról zarządzanych.','/rola nadaj|zdejmij osoba:@osoba rola:@rola','Rola musi być niżej niż rola bota oraz wykonawcy (z wyjątkiem właściciela serwera).'),
  xp: entry('zarzadzanie',3,'Dodaj, odejmij lub ustaw XP; zsynchronizuj rolę poziomową.','/xp dodaj|odejmij|ustaw osoba:@osoba ilosc:1000','Ustawienie 0 jest dozwolone. Korekty administracyjne nie wypłacają monet za awans.'),
  monety_admin: entry('zarzadzanie',3,'Dodaj, odejmij lub ustaw saldo wirtualnych monet.','/monety_admin dodaj|odejmij|ustaw osoba:@osoba ilosc:500','Ustawienie 0 jest dozwolone. Saldo nie spada poniżej zera; korekta trafia do logu i historii.'),
  diagnostyka: entry('zarzadzanie',3,'Sprawdź kanały, role, hierarchię i uprawnienia bota.','/diagnostyka','Pokazuje pełny raport w prywatnych kartach. Zielone ID nie zastępuje poprawnych uprawnień kanałów.'),
};
